### ISSUE TITLE
Use with other template languages (Rails, Phoenix, etc)

### ISSUE THREAD

**Issue by bradleybeddoes** [maizzle/framework#346]
```
maizzle -v
Framework v2.3.1
CLI v1.0.4
```

```
node -v
v14.14.0
```

Firstly many thanks for your efforts in building Maizzle and helping out the community.

I've scoured the docs, issues and PR looking for an answer to this, apologies if I've just stupidly overlooked something simple here.

What I am trying to do is have my email content designed in Maizzle but for transactional email push the build results into my web app as templates for its template engine to consume when deployed in production, the template languages seem to be colliding however.

An example might make this easier to visualise, what I am trying to do is make this:

```
...
<if condition="page.env === 'local'">
  <h1>Hi, Fred<h1>
</if>
<if condition="page.env === 'prod'">
  <raw>
    <h1>Hi, <%= @user.name %></h1>
  </raw>
</if>
<p class="m-0 mb-24">Please confirm your email address by clicking the button below:</p>
...
```

Output (for a `prod` configuration build) as:

```
...
<h1>Hi, <%= @user.name %></h1>
<p class="m-0 mb-24">Please confirm your email address by clicking the button below:</p>
...
```

instead the output is:

```
...
<h1>Hi, <%= @user.name="" %=""></%=></h1>
<p class="m-0 mb-24">Please confirm your email address by clicking the button below:</p>
...
```

As you can see the output inside `h1` is "corrupted" by something internally "trying to do the right thing" when what I was hoping to get with `raw` was the block being entirely untouched in the output.

As you'd expect I get `<h1>Hi, Fred</h1>` perfectly fine when serving locally using `maizzle serve`

Here is my `config.prod.js` if helpful, I have tried a number of angles to solve this so it is getting a touch messy by now:

```
/*
|-------------------------------------------------------------------------------
| Production config           https://maizzle.com/docs/environments/#production
|-------------------------------------------------------------------------------
|
| This is where you define settings that optimize your emails for production.
| These will be merged on top of the base config.js, so you only need to
| specify the options that are changing.
|
*/

module.exports = {
  build: {
    templates: {
      destination: {
        path: 'build_prod',
      },
    },
  },
  // purgeCSS: {},
  // removeUnusedCSS: {},
  // replaceStrings: false,
  // removeAttributes: [],
  // safeClassNames: {},
  // sixHex: false,
  prettify: false,
}
```

Any help on solving this would be really appreciated.

**Comment by bradleybeddoes** [comment]
I had a moment to dig into PostHTML a little and came up with the following:

```
    posthtml: {
      options: {
        quoteAllAttributes: false,
        singleTags: /^%\S*|\s*%$/,
      }
    },
```

which does correctly give me the output:

```
<h1>Hi, <%= @user.name %></h1>
<p class="m-0 mb-24">Please confirm your email address by clicking the button below:</p>
```

Is this a reasonable approach?

**Comment by bradleybeddoes** [comment]
This seems to be another possible approach by using `replaceStrings`, haven't yet(?) managed to break it.

```
module.exports = {
  build: {
    templates: {
      destination: {
        path: "build_prod",
      },
    },
    posthtml: {
      options: {
        quoteAllAttributes: true,
        singleTags: /br|img|meta|^%\S*|\s*%$/,
      },
    },
  },
  inlineCSS: {
    enabled: true,
  },
  removeUnusedCSS: {
    enabled: true,
  },
  replaceStrings: {
    '\\s(style|class)(=""|(?=>)|(?=\\s))+': "",
    '=""': "",
  },
};
```

**Comment by cossssmin** [comment]
Hey,

Normally it should just work with PostHTML's [`directives`](https://github.com/posthtml/posthtml-parser#directives) option:

```js
posthtml: {
  options: {
    directives: [
      { name: '%=', start: '<', end: '>' }
    ],
},
```

For some reason it doesn't though, it still outputs something like `Hi, <%= @user.name="" %=""></%=>`. 

I've tested thoroughly and I can't see it coming from other parts of Maizzle - I disabled all transformers and anything else that might manipulate HTML, even tested with [all PostHTML plugins removed](https://github.com/maizzle/framework/blob/master/src/generators/posthtml.js#L31-L46) when rendering with PostHTML.

What's really weird is that if you modify [this test](https://github.com/posthtml/posthtml/blob/f00ccf944a121060868db1b7a409aa1c3d4ac435/test/options.js#L82) in PostHTML to work with these `<%=` `%>` tags, it works - and I have no idea why it doesn't in Maizzle, not even when the `posthtml()` build process is identical to the one in that test 😐

@Scrum do you have any insight as to why it wouldn't work with `directives` like that?

**Comment by cossssmin** [comment]
@bradleybeddoes a quick solution would be to use some made-up tags/delimiters that you then replace with `replaceStrings`:

```html
<h1>Hi, !%= @user.name %!</h1>
```

```js
replaceStrings: {
  '!%=': "<%=",
  '%!': "%>",
},
```

**Comment by cossssmin** [comment]
Looks like it's fixed in `posthtml-parser@0.5.1`, just tested and it worked fine, didn't even had to use the `directives` option. For some reason we were stuck with `posthtml-parser@0.5.0` even though the latest `poshtml` (which we do use) requires `0.5.1` 🤷‍♂️

@bradleybeddoes try removing the `package-lock.json` and your `node_modules`, then `npm install` again so you get `posthtml-parser@0.5.1` (check it by running `npm list posthtml-parser`).

**Comment by bradleybeddoes** [comment]
Thank you so much for your help with this @cossssmin 🏆

I can confirm that by removing `package-lock.json` and `node_modules` to force the appropriate update of `posthtml-parser` all is working exactly as I had hoped it would within the `<raw>` block ready for feeding into my app.

**Comment by cossssmin** [comment]
Happy to help :) 

Tip: you don't need the `<raw>` tag unless you're using `{{ }}` or other `posthtml-expressions` tags that you'd like to keep ([docs](https://maizzle.com/docs/templates/#curly-brace-conflicts)).

**Comment by cossssmin** [comment]
@bradleybeddoes published [`v2.3.2`](https://github.com/maizzle/framework/releases/tag/v2.3.2)

**Comment by chasegiunta** [comment]
@cossssmin I'm actually still seeing this on a new Maizzle install. Been fighting it the past two days but I'm at wits end.
A simple example:
```
<title><%= @title %></title>

<title><%= @title="" %=""></%=></title>
```

@bradleybeddoes You're not still having issues with this?!

**Comment by bradleybeddoes** [comment]
No problems here, update fixed my issue completely 🤔.

**Comment by chasegiunta** [comment]
@bradleybeddoes do you mind sharing your config.js? Can't understand why I'm still seeing this.

**Comment by cossssmin** [comment]
Can confirm it's an issue with Maizzle 3.0, I think this bug has multiple causes. Could be `posthtml-parser@0.6.0` since it upgraded to `htmlparser2@5.0.1`, but CSS inlining also has something to do with it  (mainly because Juice uses a different HTML parser...)

For example, with inlining enabled, this:

```html
<title><%= @title %></title>
```

... is rendered as:

```html
<title><%= @title %></%=>
</title>
```

If you disable CSS inlining however, you get:

```html
<title><%= @title="" %=""></%=></title>
```

If we use a `<div>`:

```html
<div><%= @title %></div>
```

... it's rendered as expected, but only if inlining is enabled. Otherwise it renders as `<div><%= @title="" %=""></div>`

You could still use the `replaceStrings` trick I [mentioned above](https://github.com/maizzle/framework/issues/346#issuecomment-717873169) until we come up with a fix.

**Comment by chasegiunta** [comment]
Thanks @crosssmin, I am utilizing replaceStrings with some luck
```js
replaceStrings: {
    '%=""></%=>': "%>",
    '=""': "",
  },
```
but there's other instances, even with all applicable transformers disabled, where thing are still getting mangled, like this line:
```erb
<% if ((attachments && attachments['doc_thumb.jpg']) || @email_record) && content_for?(:document_url) %>
```
is being output as:
```erb
<% if ((attachments && attachments['doc_thumb.jpg']) || @email_record) content_for?(:document_url) %>
```
(notice the missing `&&`)

Until a fix where everything between the delimiters is completely ignored, this will be a tough one to crack.

**Comment by Scrum** [comment]
> Can confirm it's an issue with Maizzle 3.0, I think this bug has multiple causes. Could be `posthtml-parser@0.6.0` since it upgraded to `htmlparser2@5.0.1`, but CSS inlining also has something to do with it (mainly because Juice uses a different HTML parser...)
> 
> For example, with inlining enabled, this:

Confirm, the problems are related to the update `htmlparser2`

- https://github.com/fb55/htmlparser2/issues/642
- https://github.com/posthtml/posthtml-parser/issues/53

**Comment by Scrum** [comment]
i checked on current posthtml version and i get expected result

```js
const posthtml = require('posthtml') // "posthtml": "^0.14.0"

const html = `<title><%= @title %></title><div><%= @title %></div>`;
const plugins = [];
const options = {};

posthtml(plugins)
  .process(html, options)
  .then((result) =>  console.log(result.html)) // => <title><%= @title %></title><div><%= @title %></div>
```

**Comment by cossssmin** [comment]
> i checked on current posthtml version and i get expected result

@Scrum hmm, I suppose it's caused by plugins then?

```sh
$ npm list posthtml-parser
@maizzle/framework@3.0.0 F:\DEV\open-source\maizzle\framework
+-- posthtml@0.14.0
| `-- posthtml-parser@0.6.0 
+-- posthtml-expressions@1.6.2
| `-- posthtml-parser@0.5.3 
+-- posthtml-extend@0.5.2
| +-- posthtml@0.13.4
| | `-- posthtml-parser@0.5.3  deduped
| `-- posthtml-parser@0.5.3 
+-- posthtml-fetch@1.2.0
| `-- posthtml@0.13.4
|   `-- posthtml-parser@0.5.3 
+-- posthtml-markdownit@1.2.2
| +-- posthtml@0.13.4
| | `-- posthtml-parser@0.5.3  deduped
| `-- posthtml-parser@0.5.3 
+-- posthtml-mso@1.0.2
| `-- posthtml@0.13.4
|   `-- posthtml-parser@0.5.3 
+-- posthtml-postcss-merge-longhand@1.0.2
| `-- posthtml@0.13.4
|   `-- posthtml-parser@0.5.3 
+-- posthtml-safe-class-names@1.0.4
| `-- posthtml@0.13.4
|   `-- posthtml-parser@0.5.3 
`-- posthtml-url-parameters@1.0.4
  `-- posthtml@0.13.4
    `-- posthtml-parser@0.5.3
```

**Comment by Scrum** [comment]
> hmm, I suppose it's caused by plugins then?

Maybe. Each plugin can render / parse a tree and return a mutated one

**Comment by cossssmin** [comment]
Yeah, gonna have to start updating them all to use the latest `posthtml` or `posthtml-parser`, starting with `posthtml-expressions`.

**Comment by cossssmin** [comment]
Here's a list with plugins that need updating, ✔ means a new release has been published:

- [ ] posthtml-expressions
- [ ] posthtml-extend
- [ ] posthtml-fetch
- [ ] posthtml-markdownit
- [ ] posthtml-mso
- [ ] posthtml-postcss-merge-longhand
- [ ] posthtml-safe-class-names
- [ ] posthtml-url-parameters

**Comment by Scrum** [comment]
@cossssmin 
posthtml-expressions -> 1.7.0 
posthtml-extend -> 0.6.0

**Comment by cossssmin** [comment]
@chasegiunta published [`v3.0.1`](https://github.com/maizzle/framework/releases/tag/v3.0.1), should work as expected now. 

You'll need to delete your `node_modules` and `package-lock.json`, and run `npm install` again.

**Comment by chasegiunta** [comment]
@cossssmin Perfect. Looks like that works! Thank you for you help!

**Comment by cossssmin** [comment]
Awesome, closing as resolved then 👍

**Comment by dwightwatson** [comment]
I wonder if anyone here would be willing to share how they've integrated Maizzle with their backend framework - both in a conceptual sense but also what a config file might look like. I'm trying to see how best to fit Maizzle into a Rails app and integrate it with ActionMailer. Would be super interesting as a blog post.

**Comment by pau-riosa** [comment]
Hi guys do you have sample integration for Phoenix Framework? Thank you.
